jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ssm2?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 12345678


#修改访问端口 org.springframework.boot.autoconfigure.web.ServerProperties
#端口80为系统端口，可在访问时缺省
server:
  port: 8888